name:                befunsvge
version:             0.1.0.0
github:              "githubuser/befunsvge"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/befunsvge#readme>

dependencies:
- base-noprelude >= 4.7 && < 5
- aeson
- base64-bytestring
- containers
- hsnoise
- optparse-applicative
- optparse-generic
- random
- relude
- text

default-extensions:
 - DeriveAnyClass
 - DeriveGeneric
 - DerivingStrategies
 - FlexibleContexts
 - FlexibleInstances
 - FunctionalDependencies
 - GeneralizedNewtypeDeriving
 - LambdaCase
 - MultiParamTypeClasses
 - NamedFieldPuns
 - OverloadedLabels
 - OverloadedStrings
 - RecordWildCards
 - ScopedTypeVariables
 - TypeApplications
 - TypeFamilies
 - UndecidableInstances

library:
  source-dirs: src

executables:
  befunsvge-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - befunsvge

  svg-test-exe:
    main:                Main.hs
    source-dirs:         svg-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - befunsvge

  befunsvge-server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - befunsvge
    - http-api-data
    - lucid
    - servant
    - servant-lucid
    - servant-server
    - warp

tests:
  befunsvge-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - befunsvge
